var server  = require("./service/server")  ;  
var router = require("./service/route");  
var requestHandlers = require("./service/requestHandlers");
var apiHandlers = require("./service/apiHandlers");
  
//创建handle映射类，就是将请求路径和具体的action函数进行映射关联
  
var handle = {
	"/":requestHandlers.start,
	"/register":requestHandlers.register,
	"/start":requestHandlers.start,
	"/upload":requestHandlers.upload,
	
	"/client":requestHandlers.client,
	"/image":requestHandlers.image,
	"/db-test":requestHandlers.dbTest,
	"lib":requestHandlers.lib,
	"web":{
		"auth":{
			"register":requestHandlers.register,
			'login':requestHandlers.login
		},
		"message":{
			"sendhelp":requestHandlers.sendHelp,
			"receive":requestHandlers.myReceive,
			"help":requestHandlers.theHelp
		},
		"discover":{
			"setposition":requestHandlers.setPosition,
			"finduser":requestHandlers.findUserInArea,
			"findmessage":requestHandlers.findMessageInArea
		},
		"test":{
			"yzhu-test":requestHandlers.yzhuTest
		},
	},
	"forPost":{
		'/image':requestHandlers.imagePost,
		'/upload':requestHandlers.uploadPost,
		"web":{
			"auth":{
				'login':requestHandlers.loginPost,
				'register':requestHandlers.registerPost
			},
			"relation":{
				"addfriend":requestHandlers.addFriendByUserIdPost,
				"addfriendbyphone":requestHandlers.addFriendByPhonePost,
				"confirmfriend":requestHandlers.confirmFriendPost,
				"friendlist":requestHandlers.friendListPost,
				"solicitlist":requestHandlers.solicitListPost
			},
			"discover":{
				"setposition":requestHandlers.setPositionPost,
				"finduser":requestHandlers.findUserInAreaPost,
				"findmessage":requestHandlers.findMessageInAreaPost,
			},
			"message":{
				"sendhelp":requestHandlers.sendHelpPost,
				"receive":requestHandlers.myReceivePost,//the message push to me
				"helpinfo":requestHandlers.helpInfoPost,
				"askquestion":requestHandlers.askQuestionPost
			},
			"group":{
				"accept":requestHandlers.acceptGroupPost,
				"wait":requestHandlers.waitGroupPost,
				"accepthelp":requestHandlers.acceptHelpPost,
				"offerhelp":requestHandlers.offerHelpPost,
				"refusetohelp":requestHandlers.refuseToHelpPost,
				"ignorehelp":requestHandlers.ignoreHelpPost
			},
			"test":{
				"yzhu-test":requestHandlers.yzhuTest
			},
		},
		'/logout':requestHandlers.logoutPost,
	},
	"api":{
		"forPost":{
			"auth":{
				"login":requestHandlers.loginPost,
				"register":requestHandlers.registerPost,
				"logout":requestHandlers.logoutPost,
				"checkphone":requestHandlers.checkPhonePost
			},
			"discover":{
				"setposition":requestHandlers.setPositionPost,
				"finduser":requestHandlers.findUserInAreaPost,
				"findmessage":requestHandlers.findMessageInAreaPost,
			},
			"message":{
				"sendhelp":requestHandlers.sendHelpPost,
				"receive":requestHandlers.myReceivePost,//the message push to me
				"helpinfo":requestHandlers.helpInfoPost,
				"askquestion":requestHandlers.askQuestionPost
			},
			"group":{
				"accept":requestHandlers.acceptGroupPost,
				"wait":requestHandlers.waitGroupPost,
				"accepthelp":requestHandlers.acceptHelpPost,
				"offerhelp":requestHandlers.offerHelpPost,
				"refusetohelp":requestHandlers.refuseToHelpPost,
				"ignorehelp":requestHandlers.ignoreHelpPost
			},
			"user":{
				"setuserinfo":requestHandlers.setUserInfoPost,
				"getuserinfo":requestHandlers.getUserInfoPost
			},
			"relation":{
				"addfriend":requestHandlers.addFriendByUserIdPost,
				"addfriendbyphone":requestHandlers.addFriendByPhonePost,
				"confirmfriend":requestHandlers.confirmFriendPost,
				"removefriend":requestHandlers.deleteFriendPost,
				"friendlist":requestHandlers.friendListPost,
				"isfriend":requestHandlers.isFriendPost,
				"addcontact":requestHandlers.addContactByUserIdPost,
				"addContactByPhone":requestHandlers.addContactByPhone,
				"confirmcontact":requestHandlers.confrimContactPost,	
				"removecontact":requestHandlers.removeContactPost,
				"iscontact":requestHandlers.isContactPost,
				"solicitlist":requestHandlers.solicitListPost
			}
		},
		"discover":{
			"setposition":requestHandlers.setPosition,
			"finduser":requestHandlers.findUserInArea,
			"findmessage":requestHandlers.findMessageInArea
		},
		"message":{
			"sendhelp":requestHandlers.sendHelp,
			"receive":requestHandlers.myReceive,
			"help":requestHandlers.theHelp
		}
	}
};
console.dir(["handle",handle]);
server.start(router.route,handle);  