//the session module for server
//just to create server
//use closure to create private  variable


//On instantiation a new session id gets generated 
//which is a random value. This random value gets 
//generated by the getRandom() method, it multiplies 
//the random number with 1e16, rounds the number 
//downward and returns it as base 36 representation 
//(toString(16) would return a hexadecimal number, 
//toString(8) an octal number, toString(10) is the 
//default behavior). The middle part of the session 
//id is the time the session was created as base 36 , 
//too. The cookie value/session id could look like 
//this one: "1rb2rgxwdm7-h9igt6kx-ebo3nwmqzv".

exports.Session = function () {
	//private function
	var getRandom = function () {
		return Math.floor(Math.random()*1e16).toString(36);
	}

	//public
	var sessionID = [];
	sessionID[0] = getRandom();
	sessionID[1] = new Date().getTime().toString(36);
	sessionID[2] = getRandom();
	this.sessionId = sessionID.join('-');

	this.doDestroy = false;

	this.toString = function () {
		return this.sessionId;
	}

	this.getTime = function () {
		return parseInt(this.sessionId.split('-')[1],36);
	}
}